electric_axles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('basket/', include('basket.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),
    path('wishlist/', include('wishlist.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.all_products, name='products'),
    path('add/', views.add_product, name="add_product"),
    path('edit/<slug:slug>/', views.edit_product, name="edit_product"),
    path('delete/<slug:slug>/', views.delete_product, name="delete_product"),
    path('<slug:slug>/', views.product_detail, name="product_detail"),
    path('add_review/<slug:slug>/', views.add_review, name='add_review'),
    path(
        'edit_review/<int:review_id>/', views.edit_review, name='edit_review'),
    path(
        'delete_review/<int:review_id>/', views.delete_review,
        name='delete_review')
]

checkout/models.py
import uuid

from django.db import models
from django.db.models import Sum
from django.conf import settings
from django_countries.fields import CountryField
from products.models import Product
from profiles.models import UserProfile


class Order(models.Model):
    """
    Model that deals with the order for items
    """
    order_number = models.CharField(max_length=50, null=False, editable=False)
    user_profile = models.ForeignKey(
        UserProfile, on_delete=models.SET_NULL, null=True,
        blank=True, related_name='orders')
    full_name = models.CharField(max_length=50, null=False, blank=False)
    email = models.EmailField(max_length=250, null=False, blank=False)
    phone_number = models.CharField(max_length=20, null=False, blank=False)
    country = CountryField(blank_label='Country*', null=False, blank=False)
    postcode = models.CharField(max_length=20, null=True, blank=True)
    town_or_city = models.CharField(max_length=50, null=False, blank=False)
    postcode = models.CharField(max_length=20, null=False, blank=False)
    street_address1 = models.CharField(max_length=100, null=False, blank=False)
    street_address2 = models.CharField(max_length=100, null=True, blank=True)
    county = models.CharField(max_length=80, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    delivery_cost = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, default=0)
    order_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    grand_total = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0)
    original_basket = models.TextField(null=True, blank=False, default='')
    stripe_pid = models.CharField(
        max_length=250, null=False, blank=False, default='')
    objects = models.Manager()

    def _generate_order_number(self):
        """
        Generate a unique order number using UUID
        """
        return uuid.uuid4().hex.upper()

    def update_total(self):
        """
        Update the grand total each time a line
        item is added, accounting for delivert cost
        """
        self.order_total = (
            self.lineitems.aggregate(Sum(
                'lineitem_total'))['lineitem_total__sum'] or 0)
        if self.order_total < settings.FREE_DELIVERY_THRESHOLD:
            self.delivery_cost = (
                self.order_total * settings.STANDARD_DELIVERY_PERCENTAGE / 100)
        else:
            self.delivery_cost = 0
        self.grand_total = self.order_total + self.delivery_cost
        self.save()

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the order number
        if it hasn't been set already.
        """
        if not self.order_number:
            self.order_number = self._generate_order_number()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.order_number


class OrderLineItem(models.Model):
    """
    Model for orderlineitems
    """
    order = models.ForeignKey(
        Order, null=False, blank=False, on_delete=models.CASCADE,
        related_name='lineitems')
    product = models.ForeignKey(
        Product, null=False, blank=False, on_delete=models.CASCADE)
    product_size = models.CharField(max_length=2, null=True, blank=True)
    quantity = models.IntegerField(null=False, blank=False, default=0)
    lineitem_total = models.DecimalField(
        max_digits=6, decimal_places=2, null=False, blank=False,
        editable=False)

    def save(self, *args, **kwargs):
        """
        Override the original save method to set the lineitem total
        and update the order total.
        """
        self.lineitem_total = self.product.price * self.quantity
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Item {self.product.name} on order {self.order.order_number}'

products/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    """A model for product categories"""
    name = models.CharField(max_length=250, db_index=True)
    objects = models.Manager()

    class Meta:
        """ Correct plural for category in admin"""
        verbose_name_plural = 'categories'

    def __str__(self):
        return str(self.name)


class Product(models.Model):
    """A model for the products"""
    category = models.ForeignKey(
        Category, null=True, blank=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    rating = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    has_sizes = models.BooleanField(default=False, null=True, blank=True)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()

    class Meta:
        """Order by product created"""
        ordering = ('-created',)

    def get_absolute_url(self):
        """
        Creates dynamic urls for products
        """
        return reverse('product_detail', args=[self.slug])

    def __str__(self):
        return str(self.name)


class ProductReview(models.Model):
    """A model for product reviews"""
    product = models.ForeignKey(
        Product, null=True, blank=True, on_delete=models.SET_NULL,
        related_name='reviews')
    user = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    body = models.TextField()
    select_rating = (
        (5, '5'),
        (4, '4'),
        (3, '3'),
        (2, '2'),
        (1, '1'),
    )
    rating = models.IntegerField(choices=select_rating, default=3)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Data ordering"""
        ordering = ['-date_added']

    def __str__(self):
        return str(self.title)

products/forms.py
from django import forms
from .models import Product, ProductReview


class ProductForm(forms.ModelForm):
    """Form to add/edit products"""
    class Meta:
        """Form data"""
        model = Product
        fields = (
            'category', 'name', 'slug', 'description', 'price',
            'rating', 'image', 'has_sizes', 'in_stock')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control mb-3'


class ReviewForm(forms.ModelForm):
    """Form to add/edit products"""
    class Meta:
        """Form data"""
        model = ProductReview
        fields = ('title', 'body', 'rating', )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        placeholders = {
            'title': 'Title',
            'body': 'Write Something about the product',
            'rating': 'rating',
        }

        for field in self.fields:
            placeholder = placeholders[field]
            self.fields[field].widget.attrs['placeholder'] = placeholder
            self.fields[field].label = False
            self.fields[field].widget.attrs['class'] = 'form-control mb-3'

products/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.db.models.functions import Lower
from .models import Product, Category, ProductReview
from .forms import ProductForm, ReviewForm


def all_products(request):
    """
    A view to show all products
    """
    products = Product.objects.all()
    query = None
    all_categories = None
    sort = None
    direction = None

    if request.GET:
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            if sortkey == 'name':
                sortkey = 'lower_name'
                products = products.annotate(lower_name=Lower('name'))
            if sortkey == 'category':
                sortkey = 'category__name'
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            products = products.order_by(sortkey)

        if 'category' in request.GET:
            all_categories = request.GET['category'].split(',')
            products = products.filter(category__name__in=all_categories)
            all_categories = Category.objects.filter(name__in=all_categories)

        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(
                    request, "You didn't enter any search criteria!")
                return redirect(reverse('products'))

            queries = Q(
                name__icontains=query) | Q(description__icontains=query)
            products = products.filter(queries)

    current_sorting = f'{sort}_{direction}'

    return render(request, 'products/products.html', {
        'products': products, 'search_term': query,
        'current_categories': categories, 'current_sorting': current_sorting})


def product_detail(request, slug):
    """
    A view to show the product detail on their own page
    """
    product = get_object_or_404(Product, slug=slug, is_active=True)
    form = ReviewForm()
    return render(
        request, 'products/product_detail.html', {
            'product': product, 'form': form})


def categories(request):
    """
    A view to show all categories, for now
    """
    return {
        'categories': Category.objects.all()
    }


@login_required
def add_product(request):
    """Add a product to the store"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store management can do that.')
        return redirect(reverse('home'))

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save()
            messages.info(request, f'Successfully added product \
                 {product.name}')
            return redirect(reverse('product_detail', args=[product.slug]))
        else:
            messages.error(request, 'Failed to add product due \
                to invalid form.')
    else:
        form = ProductForm()

    template = 'products/add_product.html'
    context = {
        'form': form,
    }

    return render(request, template, context)


@login_required
def edit_product(request, slug):
    """Edit a product from the store"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store management can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, slug=slug)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            messages.info(request, f"Successfully updated product \
                {product.name}'s details")
            return redirect(reverse('product_detail', args=[product.slug]))
        else:
            messages.error(request, 'Failed to edit product due to \
                invalid form.')
    else:
        form = ProductForm(instance=product)
        messages.info(request, f"You are editing product {product.name}'s \
            details")

    template = 'products/edit_product.html'
    context = {
        'form': form,
        'product': product,
    }

    return render(request, template, context)


@login_required
def delete_product(request, slug):
    """Delete a product from the store"""
    if not request.user.is_superuser:
        messages.error(request, 'Sorry, only store management can do that.')
        return redirect(reverse('home'))

    product = get_object_or_404(Product, slug=slug)
    if request.method == 'POST':
        product.delete()
        messages.success(request, f'Product {product.name} Deleted!')
        return redirect(reverse('products'))
    else:
        messages.info(request, f"You are about to delete {product.name} \
            from the store")

    return render(
        request, 'products/delete_product.html', {'product': product})


@login_required
def add_review(request, slug):
    """
    A view for the user to create a review for a product
    """
    product = get_object_or_404(Product, slug=slug)
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ReviewForm(request.POST)
            if form.is_valid():
                review = form.save(commit=False)
                review.product = product
                review.user = request.user
                review.save()
                messages.success(request, f'Your review called {review.title} for {review.product} \
                    has been Posted Successfully')
                return redirect(reverse('product_detail', args=[product.slug]))
            else:
                messages.error(request, 'Failed to post Review, \
                    please try again later')

    return render(request, {'form': form})


@login_required
def edit_review(request, review_id):
    """
    A view for the user to edit a review for a product
    """
    review = get_object_or_404(ProductReview, pk=review_id)
    product = review.product

    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            messages.info(request, f'Your Review Called {review.title} has been \
                updated Successfully')
            return redirect(reverse('product_detail', args=[product.slug]))
        else:
            messages.error(request, 'Review edit failed, \
                please try again later')
    else:
        form = ReviewForm(instance=review)

    messages.info(request, f'You are editing your review called \
        {review.title}')
    template = 'products/product_detail.html'

    return render(request, template, {
        'form': form, 'review': review, 'product': product,
        'edit': True})


@login_required
def delete_review(request, review_id):
    """Delete"""
    review = get_object_or_404(ProductReview, pk=review_id)
    product = review.product
    review.delete()
    messages.success(request, f'Your review called {review.title} \
        has been deleted successfully')
    return redirect(reverse('product_detail', args=[product.slug]))

products/templates/products/add_product.html
{% extends "base.html" %}
{% load static %}

<title>{% block extra_title %}Management - {% endblock %}</title>

{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 col-lg-8 offset-lg-2">
            <div class="ibox">
                <div class="ibox-title">
                    <h3>Product Management</h3>
                </div>
                <div class="ibox-content">
                    <h5 class="text-muted">Add a Product</h5>
                    <form method="POST" action="{% url 'add_product' %}" class="form mb-2" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}
                            {% if field.name != 'image' %}
                                {{ field | as_crispy_field }}
                            {% else %}
                                {{ field }}
                            {% endif %}
                        {% endfor %}
                        <div class="d-grid d-md-flex justify-content-md-end py-2">
                            <a class="btn btn-outline-danger text-uppercase rounded-0 fw-bold me-md-2" href="{% url 'products' %}">Cancel</a>
                            <button type="submit" class="fw-bold btn btn-outline-dark rounded-0 text-uppercase me-md-2">Add Product</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block postloadjs %}
    {{ block.super }}
    <script>
        $('#new-image').change(function() {
            var file = $('#new-image')[0].files[0];
            $('#filename').text(`Image will be set to: ${file.name}`);
        });
    </script>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

<title>{% block extra_title %}{{ product.name }} - {% endblock %}</title>

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %} 

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-4 offset-lg-2">
                <div class="image-container my-5">
                    {% if product.image %}
                        <a href="{{ product.image.url }}" target="_blank" rel="noopener" aria-label="Product image (opens in a new tab)">
                            <img class="card-img-top img-fluid" src="{{ product.image.url }}" alt="{{ product.name }}">
                        </a>
                    {% else %}
                        <a href="">
                            <img class="card-img-top img-fluid" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="{{ product.name }}">
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-6 col-lg-4 py-5">
                <div class="product-details-container mb-5 mt-md-5">
                    <h2 class="display-5 fw-bolder">{{ product.name|upper }}</h2>
                    <p class="lead mb-0 fw-bold">£{{ product.price }}</p>
                    {% if product.rating %}
                        <small class="text-muted"><i class="fas fa-star mr-1"></i>{{ product.rating }} / 5</small>
                    {% else %}
                        <small class="text-muted">No Rating</small>
                    {% endif %}
                    {% if product.category %}
                        <p class="small mt-1">
                            <a class="text-muted" href="{% url 'products' %}?category={{ product.category.name }}">
                                <i class="fas fa-tag mr-1"></i>{{ product.category.name }}
                            </a>
                        </p>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <small>
                            <a class="text-primary" href="{% url 'edit_product' product.slug %}">Edit</a> |
                            <a class="text-danger" href="{% url 'delete_product' product.slug %}">Delete</a>
                        </small>
                    {% endif %}
                    <p class="mt-3">{{ product.description }}</p>
                    <form class="form" action="{% url 'add_to_basket' product.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-row">
                            {% if product.in_stock %}
                                {% with product.has_sizes as size %}
                                    {% if size %}
                                        <div class="col-12">
                                            <p><strong>Size:</strong></p>
                                            <select class="form-control rounded-0 w-50" name="product_size" id="id_product_size">
                                                <option value="s">S</option>
                                                <option value="m" selected>M</option>
                                                <option value="l">L</option>
                                                <option value="xl">XL</option>
                                            </select>
                                        </div>
                                    {% endif %}
                                {% endwith %}
                                <div class="col-12">
                                    <p class="mt-3"><strong>Quantity:</strong></p>
                                    <div class="form-group w-50">
                                        <div class="input-group input-group-{{ product.id }}">
                                            <div class="input-group-prepend">
                                                <button class="decrement-qty btn btn-dark rounded-0 decrement-qty_{{ product.id }}" data-item_id="{{ product.id }}">
                                                    <span class="icon">
                                                        <i class="fa-solid fa-caret-left"></i>
                                                    </span>
                                                </button>
                                            </div>
                                            <input class="form-control qty_input id_qty_{{ product.id }}" type="number" name="quantity" value="1" min="1" max="20" data-item_id="{{ product.id }}">
                                            <div class="input-group-append">
                                                <button class="increment-qty btn btn-dark rounded-0 increment-qty_{{ product.id }}"
                                                    data-item_id="{{ product.id }}">
                                                    <span class="icon">
                                                        <i class="fa-solid fa-caret-right"></i>
                                                    </span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>   
                                </div>
                                <div class="col-12">
                                    {% if request.user.is_authenticated %}
                                        <a class="fw-bold btn btn-outline-dark rounded-0 text-uppercase mt-5" href="{% url 'add_to_wishlist' product.slug %}">
                                            Add to Wishlist
                                        </a>
                                    {% endif %}
                                    <input type="submit" class="fw-bold btn btn-outline-dark rounded-0 text-uppercase mt-5" value="Add to Basket">
                                    <input type="hidden" name="redirect_url" value="{{ request.path }}">
                                </div>
                            {% else %}
                                <div class="col-12">
                                    {% if request.user.is_authenticated %}
                                        <p class="mt-5 text-danger">Item currently not in stock</p>
                                        <a class="fw-bold btn btn-outline-dark rounded-0 text-uppercase" href="{% url 'add_to_wishlist' product.slug %}">
                                            Add to Wishlist
                                        </a>
                                    {% else %}
                                        <p class="mt-2 text-danger">Item currently not in stock</p>
                                    {% endif %}
                                </div>
                            {% endif %}
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 col-md-12 col-lg-4 offset-lg-1 mt-3">
                <div id="reviews" class="ibox">
                    {% if request.user.is_authenticated %}
                        {% if edit %}
                        <div class="ibox-title">
                            <h2 class="text-black text-center fw-bold">Edit A Review</h2>
                        </div>
                        <div class="ibox-content">
                            <form method="POST" class="align-items-center" action="{% url 'edit_review' review.id %}#reviews">
                                {% csrf_token %}
                                {{ form | crispy }}
                                <div class="d-flex justify-content-between">
                                    <a class="fw-bold btn btn-outline-danger rounded-0 text-uppercase" href="{% url 'delete_review' review.id %}#reviews">
                                        Delete
                                    </a>
                                    <button class="fw-bold btn btn-outline-dark rounded-0 text-uppercase" type="submit">Update Review</button>
                                </div>
                            </form>
                        </div>
                        {% else %}
                            <div class="ibox-title">
                                <h2 class="text-black text-center fw-bold">Write A Review</h2>
                            </div>
                            <div class="ibox-content">
                                <form method="POST" class="align-items-center" action="{% url 'add_review' product.slug %}">
                                    {% csrf_token %}
                                    {{ form | crispy }}
                                    <div class="d-flex justify-content-end">
                                        <button class="fw-bold btn btn-outline-dark rounded-0 text-uppercase mt-2" type="submit">Submit</button>
                                    </div>
                                </form>
                            </div>
                        {% endif %}
                    {% else %}
                        <div class="ibox-title">
                            <h2 class="text-black text-center fw-bold">Write A Review</h2>
                        </div>
                        <div class="ibox-content">
                            <p class="small"> You must <a href="{% url 'account_login' %}">Login</a> to leave a comment or <a href="{% url 'account_signup' %}">Register</a> if you dont have an account</p>
                        </div>   
                    {% endif %}
                </div>
            </div>
            <div class="col-12 col-md-12 col-lg-7 mt-3">
                <div class="ibox">
                    <div class="ibox-title">
                        <h2 class="text-black text-center fw-bold">Customer Reviews</h2>
                    </div>
                    <div class="ibox-content">
                        {% for review in product.reviews.all %}
                            <div class="card review-container mt-5">
                                <div class="card-body">
                                    <p class="card-title">{{ review.title }}</p>
                                    <p class="card-title"><i class="ml-5 fas fa-star"></i> {{ review.rating }}/5</p>
                                    <p class="card-text lead">{{ review.body }}</p>
                                    <p class="small text-muted"> by {{ review.user }} on {{ review.date_added|date:"d-m-Y"}}</p>    
                                </div>
                                <div class="col-12 px-2 py-2">
                                    {% if review.user == request.user or request.user.is_superuser %}
                                        <a class="fw-bold btn btn-outline-primary rounded-0 text-uppercase" href="{% url 'edit_review' review.id %}#reviews">
                                            Edit
                                        </a>
                                        <a class="fw-bold btn btn-outline-danger rounded-0 text-uppercase" href="{% url 'delete_review' review.id %}#reviews">
                                            Delete
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        {% empty %}
                            <div class="text-center">
                                <p>No reviews for this product</p>
                            </div>    
                        {% endfor%}  
                    </div>
                </div>        
            </div>
        </div>
    </div>
{% endblock %}

{% block postloadjs %}
{{ block.super }}
{% include 'products/includes/quantity_input_script.html' %}
{% endblock %}